name: Docs building

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-docs:
    strategy:
      matrix:
        os: [ linux ]
        compiler:
          - { distro: "debian:unstable-slim", family: LLVM, version: 18, CC: clang-18, CXX: clang++-18 }
        flavor: [ WWW ]
    uses: ./.github/workflows/CI-linux.yml
    with:
      os: ${{ matrix.os }}
      distro: ${{ matrix.compiler.distro }}
      compiler-family: ${{ matrix.compiler.family }}
      compiler-version: ${{ matrix.compiler.version }}
      compiler-CC: ${{ matrix.compiler.CC }}
      compiler-CXX: ${{ matrix.compiler.CXX }}
      flavor: ${{ matrix.flavor }}
  publish-pages:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
